# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       a10disp

# >> macros
# << macros

Summary:    Tool for display on A10 boards
Version:    0.3.2
Release:    1
Group:      System/Boot
License:    GPLv2
URL:        http://linux-sunxi.org
Source0:    %{name}-%{version}.tar.bz2
#Source100:  sunxi-boards-eoma68.yaml
BuildRequires:  sunxi-tools

%description
Tool to change display resolution on A10 Arm boards



%prep
%setup -q -n %{name}-%{version}/a10disp

# >> setup
# << setup

%build
# >> build pre
make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
mkdir -p %{buildroot}/%{_bindir}/
cp -a a10disp %{buildroot}/%{_bindir}
# << install post


%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/a10disp
# << files
